---
title: "San Francisco Estuary POTW Data"
output: 
  flexdashboard::flex_dashboard:
    social: menu
    source_code: "https://github.com/fawda123/SFPOTW"
    logo: www/sfeilogo.png
runtime: shiny
css: styles.css
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = F, message = F, warning = F)

# libraries
library(flexdashboard)
library(shinyWidgets)
library(shiny)
library(dplyr)

source('R/funcs.R')

load('data/loads.RData')

param <- sort(unique(loads$param))
potw <- sort(unique(loads$POTW))
subm <- sort(unique(loads$sub_name))

# placeholder vector for monthly selection
mos <- c('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec')
```

```{r reactives}
# potw subset data
potwseldat <- reactive({
  
  # inputs
  potwsel1 <- input$potwsel1
  paramsel1 <- input$paramsel1
  
  out <- subset(loads, POTW == potwsel1 & param == paramsel1)
  
  return(out)
  
})

# potw plot
potwplo <- reactive({
  
  # inputs
  potwseldat <- potwseldat()
  sumsel1 <- as.logical(input$sumsel1)
  yearsel1 <- input$yearsel1

  plo_fun(potwseldat, sumsel1, yearsel1)  

})

# submbayment subset data
submseldat <- reactive({
  
  # inputs
  submsel1 <- input$submsel1
  potwsel2 <- input$potwsel2
  paramsel2 <- input$paramsel2
  
  validate(
    need(potwsel2, 'Need at least one POTW'),
  )
  
  out <- subset(loads, sub_name == submsel1 & param == paramsel2 & POTW %in% potwsel2)
  out <- summarise(out, 
                   mag = sum(mag, na.rm = T), 
                   .by = c('month', 'year', 'date', 'param'))
  
  return(out)
  
})

submplot <- reactive({
  
  # inputs
  submseldat <- submseldat()
  sumsel2 <- as.logical(input$sumsel2)
  yearsel2 <- input$yearsel2
  
  plo_fun(submseldat, sumsel2, yearsel2)
  
})
```


BY POTW
===========================================================

Column 
-----------------------------------------------------------------------

### View results

```{r}
output$potwplo <- plotly::renderPlotly(potwplo())
fillCol(flex = c(NA, NA, 1),
  column(12, 
    column(4, tags$div(title = "Select the POTW of interest", 
      selectInput("potwsel1", "POTW", choices = potw, width = '100%'))
    ),
    column(4, tags$div(title = "Select the parameter of interest", 
      selectInput("paramsel1", "Parameter", choices = param, width = '100%'))
    )
  ),
  column(12,
    column(2, tags$div(title = "Select yes/no to summarise data annually"), 
      selectInput("sumsel1", "Summarise annually?", choices = c('Yes' = T, 'No' = F), selected = F, width = '100%')
    ), 
    column(6, renderUI({
      
      # input
      sumsel1 <- as.logical(input$sumsel1)
      if(sumsel1){
        tags$div(title = "Select the annual range of interest", 
          sliderTextInput("yearsel1", "Month range", choices = mos, selected = mos[c(1, 12)], width = '100%', grid = T))
      }
      
      })
    )
  ),
  plotly::plotlyOutput("potwplo")
)
```

BY SUBEMBAYMENT
===========================================================

Column
-------------------------------------

### View results

```{r}
output$submplot <- plotly::renderPlotly(submplot())
fillCol(flex = c(NA, NA, 1), 
  column(12, 
    column(4, tags$div(title = "Select the sub-embayment of interest, POTW selection will be filtered accordingly", 
      selectInput("submsel1", "Sub-embayment", choices = subm, width = '100%'))
    ),
    column(4, renderUI({
      
           # input
           submsel1 <- input$submsel1
           tosel <- sort(unique(subset(loads, sub_name == submsel1)$POTW))
           
           tags$div(title = "Select the POTWs of interest, remove a POTW by clicking and hitting backspace",
              selectInput("potwsel2", "POTW", choices = tosel, width = '100%', multiple = T, selected = tosel)
           )
           
         })),
    column(4, tags$div(title = "Select a paramater of interest", 
      selectInput("paramsel2", "Parameter", choices = param, width = '100%'))
    )
  ),
  column(12,
    column(2, tags$div(title = "Select yes/no to summarise data annually"), 
      selectInput("sumsel2", "Summarise annually?", choices = c('Yes' = T, 'No' = F), selected = F, width = '100%')
    ), 
    column(6, renderUI({
      
      # input
      sumsel2 <- as.logical(input$sumsel2)
      if(sumsel2){
        tags$div(title = "Select the annual range of interest", 
          sliderTextInput("yearsel2", "Month range", choices = mos, selected = mos[c(1, 12)], width = '100%', grid = T))
      }
      
      })
    )
  ),
  plotly::plotlyOutput("submplot")
)
```

